version: "3.7"

services:
  proxy:
    build: ./proxy/
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/mask-ip.js:/etc/nginx/mask-ip.js
      - ./proxy/dbip-city-lite-2020-09.mmdb:/etc/dbip-city-lite.mmdb
    ports:
      - 8080:80

  backend1:
    image: nginx
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/wwwroot/:/usr/share/nginx/html/

  web:
    build: ./nodejs/
